import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";
import unusedImports from "eslint-plugin-unused-imports";

/**
 * Tuned for a 4-hour hackathon with AI assistance in the loop.
 *
 * ERROR  = this will bite you at the demo (silent data loss, wrong types,
 *          promises that never run). Fix it, do not disable it.
 * WARN   = code smell that piles up. Clean it if you have a minute.
 *
 * A config that shouts constantly gets bypassed with --no-verify, so anything
 * merely stylistic is deliberately left out.
 */
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/components/ui/**", // generated by shadcn -- re-add, do not hand-edit
  ]),

  // ---------------------------------------------------------------------
  // Type-aware rules. These need the TS program, hence projectService.
  // ---------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx}"],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { "unused-imports": unusedImports },
    rules: {
      // -- Async correctness. The single biggest source of "it worked locally".
      // A forgotten `await` on a db call means the write races the response.
      // checkThenables is REQUIRED here: Drizzle query builders are custom
      // thenables, not real Promises, so the default setting misses
      // `db.insert(...)` with no await -- the exact bug this rule is for.
      "@typescript-eslint/no-floating-promises": [
        "error",
        { checkThenables: true },
      ],
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/require-await": "warn",

      // -- Type honesty. `any` silently switches off every rule below it.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-unsafe-return": "error",
      // `!` is how AI silences a null check it did not understand.
      "@typescript-eslint/no-non-null-assertion": "warn",

      // -- Dead code. AI leaves scaffolding behind on every edit.
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          args: "after-used",
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      // -- Pointless defensive code: checks that can never be false, `?.` on a
      // value the types say is always present, `catch { throw }` wrappers.
      "@typescript-eslint/no-unnecessary-condition": "warn",
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      "@typescript-eslint/no-useless-empty-export": "warn",
      "no-useless-catch": "error",
      "no-useless-rename": "warn",

      // -- Leftovers from debugging.
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "no-alert": "error",

      // -- Correctness basics.
      eqeqeq: ["error", "always", { null: "ignore" }],
      "prefer-const": "error",
      "no-var": "error",
      "@typescript-eslint/no-shadow": "warn",

      // -- Silencing the linter must be justified in writing.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        { "ts-expect-error": "allow-with-description", "ts-ignore": true },
      ],
    },
  },

  // ---------------------------------------------------------------------
  // Architectural guardrails specific to this project.
  // ---------------------------------------------------------------------
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/db/client",
              message:
                "Import { db } from '@/db' instead. '@/db/client' skips the server-only guard and is for Node scripts (seed) only.",
            },
          ],
          patterns: [
            {
              group: ["../../*"],
              message:
                "Reaching up two levels means the file is in the wrong folder. Use the '@/' alias.",
            },
          ],
        },
      ],
      // AI reaches for useEffect to fetch data; in the App Router that data
      // should be loaded in a Server Component instead.
      "no-restricted-syntax": [
        "warn",
        {
          selector:
            "CallExpression[callee.name='useEffect'] CallExpression[callee.name='fetch']",
          message:
            "Do not fetch in useEffect. Load data in a Server Component, or mutate with a Server Action.",
        },
        {
          selector: "TSEnumDeclaration",
          message:
            "Use a union type or an `as const` object instead of an enum.",
        },
      ],
    },
  },

  // Node scripts and config files are allowed to log and to use the raw client.
  {
    files: [
      "src/db/seed.ts",
      "src/db/client.ts",
      "*.config.{ts,mjs,js}",
      "drizzle.config.ts",
    ],
    rules: {
      "no-console": "off",
      "no-restricted-imports": "off",
    },
  },
]);

export default eslintConfig;
